name: flutter_keyboard_size
description: A straightforward and convenient provider that helps get info about - keyboard height, is it open or not, set bool value is screen small or not.
version: 1.0.0
homepage: https://github.com/awaik/flutter_keyboard_size

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
