name: flutter_keyboard_size
description: A straightforward and convenient provider that helps get info about - keyboard height, is it open or not, set bool value is screen small or not.
version: 0.1.2
homepage: https://github.com/awaik/flutter_keyboard_size

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
